#!/usr/bin/env bash
# Install Nginx Server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html
sudo sed -i '/server.name..;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
