#!/usr/bin/env bash
# Install Nginx Server

sudo apt-get -y update
sudo apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
sudo sed -i '/server.name..;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx start

