#!/usr/bin/env bash
# Install Nginx Server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo sed -i '/server.name..;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo touch /var/www/html/error.html
sudo chmod 666 /var/www/html/error.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
sudo sed -i '/server.name..;/a \        error_page 404 /error.html;\n   location = /error.html {\n              root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/a \        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
service nginx start
