#!/usr/bin/env bash
# Install and configure HAProxy 

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "
frontend http_front
  bind *:80
	mode http
  default_backend web-backend
backend web-backend
  balance roundrobin
  server 4585-web-01 18.215.143.86:80 check
  server 4585-web-02 50.19.37.76:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
