#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times

x=0
while [ $x -lt 10 ]
do
    echo "Best School"
    if [ $x -eq 8 ]
    then
        echo "Hi"
    fi
    x=$(( x + 1 ))
done
